BookSelling/BookSelling/Controllers/AdvertisementsController.cs
using BookSelling.Data;
using BookSelling.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookSelling.Data;
using BookSelling.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BookSelling.Controllers
{
    public class AdvertisementsController : Controller
    {

        /// <summary>
        /// this attribute refers the database of our project
        /// </summary>
        private readonly ApplicationDbContext _context;

        private readonly IWebHostEnvironment _webHostEnvironment;

        /// <summary>
        /// variavel que recolhe os dados da pessoa que se autenticou
        /// </summary>
        private readonly UserManager<IdentityUser> _userManager;

        public AdvertisementsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;

        }

        // GET: Advertisements
        public async Task<IActionResult> Index()
        {

            /* execute the db command
             * select *
             * from Advertisements
             * 
             * and send Data to View
             */
            var applicationDbContext = _context.Advertisement.Include(a => a.User);
            return View(await applicationDbContext.ToListAsync());
            //return View(await _context.Advertisement.ToListAsync());

        }

        /// <summary>
        /// Metodo para apresentar os comentarios feitos pelos utilizadores
  
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> CreateComentario(int IdAds, string comentario, int rating)
        {
            //recolher dados do utilizador
            var utilizador = _context.Utilizadores.Where(u => u.LinkID == _userManager.GetUserId(User)).FirstOrDefault();

            // será que este user já fez um comentário sobre este filme?
            var oldComentario = await _context.Reviews.Where(r => r.Utilizador == utilizador && r.AdsFK == IdAds).FirstOrDefaultAsync();

            if (oldComentario == null)
            {
                //variavel que contem os dados da review, do utilizador e sobre qual filme foi feita review
                var comment = new Reviews
                {
                    AdsFK = IdAds,
                    Comentario = comentario.Replace("\r\n", "<br />"),
                    Pontuacao = rating,
                    Data = DateTime.Now,
                    Visibilidade = true,
                    Utilizador = utilizador
                };
                //adiciona a review à Base de Dados
                _context.Reviews.Add(comment);
                //o utilizador já fez a sua review
                utilizador.ControlarReview = true;
                //guardar a alteração na Base de Dados
                _context.Utilizadores.Update(utilizador);
                //Guarda as alterações na Base de Dados
                await _context.SaveChangesAsync();
                //redirecionar para a página dos details do filme
                return RedirectToAction(nameof(Details), new { id = IdAds });
            }
            else
            {
                return RedirectToAction(nameof(Details), new { id = IdAds });
            }


        }

        // GET: Advertisements/Details/5
        public async Task<IActionResult> Details(int? id, int FavoriteValue)
        {
            if (id == null)
            {
                return NotFound();
            }

           

            ViewBag.FavoriteValue = 0;


            foreach (Utilizadores us in _context.Utilizadores)
            {
                foreach (var item in _context.Favorites)
                {
                    if (us.UserID == item.UtilizadoresID)
                    {
                        item.Utilizadores = us;
                    }
                }
            }

            foreach (var item in _context.Favorites)
            {
                if (User.Identity.Name == item.Utilizadores.Email)
                {
                    ViewBag.FavoriteValue = 1;
                }
            }

            var advertisement = await _context.Advertisement
                .Include(a => a.User)
                .Include(c => c.CategoriesList)
                .Include(f => f.ReviewsList)
                .ThenInclude(r => r.Utilizador)
                .FirstOrDefaultAsync(m => m.AdID == id);
            if (advertisement == null)
            {
                return NotFound();
            }

            return View(advertisement);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> AddFavorite(int id)
        {

            // if advertisement not on favorite list, button shouldn't be pressed
            // if this is true then the user already has added this advertisement to his favorite list
            var flag = 0;
            var advert = new Advertisement();
            var user = new Utilizadores();
            int iddouser = 0;
            foreach (Favorite aux in _context.Favorites)
            {
                foreach (Utilizadores us in _context.Utilizadores)
                {
                    if (us.UserID == aux.UtilizadoresID)
                    {
                        aux.Utilizadores = us;
                    }
                }
                foreach (Advertisement a in _context.Advertisement)
                {
                    if (a.AdID == aux.AdvertisementID)
                    {
                        aux.Advertisement = a;
                    }
                }
                if (aux.AdvertisementID == id && aux.Utilizadores.Email == User.Identity.Name)
                {
                    flag++;
                    _context.Remove(aux);
                }
            }
            if (flag == 0)
            {
                //this means that the advertisement is not favorite yet
                foreach (Utilizadores axax in _context.Utilizadores)
                {
                    if (axax.Email == User.Identity.Name)
                    {
                        iddouser = axax.UserID;
                        user = axax;
                    }

                }
                foreach (Advertisement ad2 in _context.Advertisement)
                {
                    if (ad2.AdID == id)
                    {
                        advert = ad2;
                    }
                }
                var favorite = new Favorite
                {
                    AdvertisementID = id,
                    Advertisement = advert,
                    Utilizadores = user,
                    UtilizadoresID = iddouser
                };

                //foreach (Advertisement ad2 in _context.Advertisement)
                //{
                //    if (ad2.AdID == id)
                //    {
                //        ad2.Favorites.Add(favorite);
                //    }
                //}

                if (ModelState.IsValid)
                {
                    try
                    {
                        //add Favorite data to database
                        _context.Add(favorite);
                        //commit
                        await _context.SaveChangesAsync();
                    }
                    catch (Exception)
                    {
                        // if the code arrives here, something wrong has appended
                        // we must fix the error, or at least report it

                        // add a model error to our code
                        ModelState.AddModelError("", "Something went wrong. I can not add it to the favorite list");
                        // eventually, before sending control to View
                        // report error. For instance, write a message to the disc
                        // or send an email to admin              

                        // send control to View
                        return RedirectToAction(nameof(Details), new { id = id });
                    }
                }

            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { id = id });
        }

        // GET: Advertisements/Create
        public IActionResult Create()
        {
            ViewData["UserID"] = new SelectList(_context.Set<Utilizadores>(), "UserID", "Email");
            return View();
        }

        // POST: Advertisements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("AdID,TypeofAdd,Title,Description,Price,ISBM,Photo,UserID,sold,Visibility,DateTime,User")] Advertisement advertisement, IFormFile newphoto, String typeAd, ICollection<String> ChoosenCategory)
        {
            ModelState.Remove("DateTime");
            ModelState.Remove("User");
            ModelState.Remove("Category");
            ModelState.Remove("Photo");

            /* we must process the image
             * 
             * if file is null
             * add a pre-define image to vet (default avatar)
             * else
             *  if file is not an image
             *  send an error message to user, asking for an image
             *  else
             *  - define the name that the image must have

BookSelling/BookSelling/Controllers/HomeController.cs
using BookSelling.Data;
using BookSelling.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Dynamic;

namespace BookSelling.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        private List<Advertisement> GetAdvertisements(ICollection<String> ChoosenCategory)
        {
            //PT->Percorrer as tabelas para adicionar a cada "ad"(Advertisement) o respetivo User
            //EN->Go through the tables to add to each "ad"(Advertisement) the respective User
            foreach (Advertisement ad in _context.Advertisement)
            {
                foreach (Utilizadores user in _context.Utilizadores)
                {
                    if (ad.UserID == user.UserID)
                    {
                        ad.User = user;
                    }
                }
            }

            foreach (AdvertsCategory adC in _context.AdvertsCategory)
            {
                foreach (Category cat in _context.Category)
                {
                    if (cat.IdCategory == adC.CategoryFK)
                    {
                        adC.Category = cat;
                    }
                }
            }
            //PT->Criar uma lista que vai receber os Ads pretendidos segundo o filtro, ou não(Caso nenhuma categoria seja escolhida)
            //EN->Create a list that will receive the pretended Ads according to the filter, or not(In the case that no category is choosen)
            List<Advertisement> ads = new List<Advertisement>();
            
            //PT->Variável auxiliar inicializada a zero para mais tarde ser usada como "flag"
            //EN->Auxiliar variable initialized at zero to later be used as a "flag"
            var aux = 0;

            //PT->Caso nenhuma categoria seja escolhida no filtro
            //EN->In case no category is choosen in the filter
            if (ChoosenCategory.Count == 0)
            {
                //PT->Cada Advertisement
                //EN->Every Advertisement
                foreach (Advertisement ad in _context.Advertisement)
                {
                    //PT->Vai ser adicionado á lista "ads"
                    //EN->Will be added to the list "ads"
                    ads.Add(ad);
                }
            }
            //PT->Caso uma ou mais categorias sejam escolhidas no filtro
            //EN->In case one or more caregories are choosen in the filter
            else
            {
                //PT->Para cada "ad"(Advertisement)
                //EN->To every "ad"(Advertisement)
                foreach (Advertisement ad in _context.Advertisement)
                {
                    //PT->Para cada categoria escolhida
                    //EN->To every category choosen
                    foreach (String category in ChoosenCategory)
                    {
                        //PT->Para cada categoria do "ad"(Advertisement)
                        //EN->To every category of "ad"(Advertisement)
                        foreach (AdvertsCategory cat in _context.AdvertsCategory)
                        {
                            //PT->Se o nome da categoria do "ad"(Advertisement) for igual á categoria escolhida
                            //EN->If the name of the category of the "ad""(Advertisement) is equal to the category choosen
                            if (cat.Advertisement == ad && cat.Category.NameCategory == category)
                            {
                                //PT->É adicionado o valor 1 á variável auxiliar
                                //EN->It's added the value 1 to the auxiliar variable
                                aux = aux + 1;
                            }
                        }
                    }
                    //PT->Depois de se ter percorrido as tabelas, se o valor da variável auxiliar for maior que zero
                    //EN->After go through the tables, if the value of the auxiliar variable is bigger than zero
                    if (aux > 0)
                    {
                        //PT->O "ad"(Advertisement) possui pelo menos uma das categorias escolhidas, logo é adicionado á lista "ads"
                        //EN->The "ad"(Advertisement) has at least one of the choosen categories, so it is added to the list "ads"
                        ads.Add(ad);
                        //PT->O valor da variável auxiliar é colocado a zero novamente
                        //EN->The value of the auxiliar variabel is reseted to zero again
                        aux = 0;
                    }
                }
            }
            //PT->Retorna a lista dos "ads" pretendidos
            //EN->Return the list of the pretended "ads"
            return ads;
        }

        public async Task<IActionResult> Index(ICollection<String> ChoosenCategory)
        {
            //PT->Criação do modelo dinamico "mymodel"
            //EN->Creation of the dynamic model "mymodel"
            dynamic mymodel = new ExpandoObject();
            //PT->Definir que o "mymodel.Advertisements" vair obter os valores retornados pelo método "GetAdvertisements(ChoosenCategory)"
            //EN->Set that the "mymodel.Advertisements" will get the values returned by the method "GetAdvertisements(ChoosenCategory)"
            mymodel.Advertisements = GetAdvertisements(ChoosenCategory);
            //PT->Retornar a view com o modelo dinamico
            //EN->Return the view with the dynamic model
            return View(mymodel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookSelling/BookSelling/Views/Home/Index.cshtml
@model dynamic


@{
    ViewData["Title"] = "Index";
}
<head>
    <link rel="stylesheet" href="~/css/ImagensFavorites.css" />
</head>

@if (User.Identity.IsAuthenticated)
{
    <button class="btn btn-primary" style="height:35px; margin-top: 15px; margin-right:10px; float:right" onclick="location.href = '@Url.Action("Create","Advertisements")'">Create Advertisement</button> 
}

<h1>Advertisements List</h1>

<body style="background-image: url('../Logos/bkteste6.jpg');
    background-repeat: repeat; background-size: 360px">
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>

    <form asp-action="Index" enctype ="multipart/form-data" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>

            <div style="border-top: 20px solid transparent;border-bottom: 5px solid transparent; width:625px">
              <div class="form-group col-sm-8">
                <label >Categories</label>
                <label for="myMultiselect"></label>
                <div id="myMultiselect" class="multiselect">
                  <div id="mySelectLabel" class="selectBox" onclick="toggleCheckboxArea()">
                    <select class="form-select">
                      <option>somevalue</option>
                    </select>
                    <div class="overSelect"></div>
                  </div>
                  <div id="mySelectOptions">
                    <label for="one"><input name="ChoosenCategory" type="checkbox" id="one" onchange="checkboxStatusChange()" value="Action" />Action</label>
                    <label for="two"><input name="ChoosenCategory" type="checkbox" id="two" onchange="checkboxStatusChange()" value="Adventure" />Adventure</label>
                    <label for="three"><input name="ChoosenCategory" type="checkbox" id="three" onchange="checkboxStatusChange()" value="Comedy" />Comedy</label>
                    <label for="four"><input name="ChoosenCategory" type="checkbox" id="four" onchange="checkboxStatusChange()" value="Drama" />Drama</label>
                    <label for="five"><input name="ChoosenCategory" type="checkbox" id="five" onchange="checkboxStatusChange()" value="Fantasy" />Fantasy</label>
                    <label for="six"><input name="ChoosenCategory" type="checkbox" id="six" onchange="checkboxStatusChange()" value="Science Fiction" />Science Fiction</label>
                    <label for="seven"><input name="ChoosenCategory" type="checkbox" id="seven" onchange="checkboxStatusChange()" value="Romance" />Romance</label>
                    <label for="eight"><input name="ChoosenCategory" type="checkbox" id="eight" onchange="checkboxStatusChange()" value="Horror" />Horror</label>
                    <label for="nine"><input name="ChoosenCategory" type="checkbox" id="nine" onchange="checkboxStatusChange()" value="Erotic" />Erotic</label>
                    <label for="ten"><input name="ChoosenCategory" type="checkbox" id="ten" onchange="checkboxStatusChange()" value="Thriller" />Thriller</label>
                    <label for="eleven"><input name="ChoosenCategory" type="checkbox" id="eleven" onchange="checkboxStatusChange()" value="Kids" />Kids</label>
                    <label for="twelve"><input name="ChoosenCategory" type="checkbox" id="twelve" onchange="checkboxStatusChange()" value="Mistery" />Mistery</label>
                    <label for="thirteen"><input name="ChoosenCategory" type="checkbox" id="thirteen" onchange="checkboxStatusChange()" value="Suspance" />Suspance</label>
                    <label for="fourteen"><input name="ChoosenCategory" type="checkbox" id="fourteen" onchange="checkboxStatusChange()" value="Comic" />Comic</label>
                  </div>
                </div>
              </div>

            </div>
            <div class="form-group">
                <input type="submit" value="Filter" class="btn btn-primary" />
            </div>
    </form>

    @foreach (Advertisement ad in Model.Advertisements) {

    <div class="Advertisement">
        <a asp-controller="Advertisements" asp-action="Details" asp-route-id="@ad.AdID" >
            <img class="PhotoAdvertisement" src="~/Photos/@Html.DisplayFor(modelItem => ad.Photo)"/>
            <div class="overlay">
                <div class="text">
                    @Html.DisplayFor(modelItem => ad.Title)
                </div>
            </div>
        </a>
    </div>}

    @*-Seacrh Bar-*@

     @*<form id="content" class="search-bar">
            <input type="text" id="search-input" onkeyup="myFunction()" placeholder="Search Your Favorite Book" title="Search books by the Name or by the Code">
            <button type="reset" class="search" id="search-btn"></button>
        </form>

        <script type="text/javascript">
        const input = document.getElementById("search-input");
        const searchBtn = document.getElementById("search-btn");
        const expand = () => {
            searchBtn.classList.toggle("close");
            input.classList.toggle("square");
        };
        searchBtn.addEventListener("click", expand);
            function myFunction() {
                var input, filter, ul, li, a, i, h, b, txtValue;
                input = document.getElementById("search-input");
                filter = input.value.toUpperCase();
                ul = document.getElementByTagName("li");
                for (i = 0; i < li.length; i++) {
                    a = li[i].getElementByTagName("a")[0];
                    txtValue = a.textContent || a.innerText;
                    if (txtValue.toUpperCase().indexOf(fliter) > -1) {
                        li[i].style.display = "";
                    }
                    else {
                        li[i].style.display = "none";
                    }
                }
            }
        </script>*@