BookSelling/BookSelling/Controllers/UserReviewsController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookSelling.Data;
using BookSelling.Models;

namespace BookSelling.Controllers
{
    public class UserReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserReviewsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UserReviews
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.UserReview.Include(u => u.Utilizador).Include(u => u.Utilizador2);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: UserReviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UserReview == null)
            {
                return NotFound();
            }

            var userReview = await _context.UserReview
                .Include(u => u.Utilizador)
                .Include(u => u.Utilizador2)
                .FirstOrDefaultAsync(m => m.IdReview == id);
            if (userReview == null)
            {
                return NotFound();
            }

            return View(userReview);
        }

        // GET: UserReviews/Create
        public IActionResult Create()
        {
            ViewData["UtilizadorFK"] = new SelectList(_context.Utilizadores, "UserID", "Area");
            ViewData["Utilizador2FK"] = new SelectList(_context.Utilizadores, "UserID", "Area");
            return View();
        }

        // POST: UserReviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdReview,ValueReview,DateReview,UtilizadorFK,Utilizador2FK")] UserReview userReview)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userReview);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UtilizadorFK"] = new SelectList(_context.Utilizadores, "UserID", "Area", userReview.UtilizadorFK);
            ViewData["Utilizador2FK"] = new SelectList(_context.Utilizadores, "UserID", "Area", userReview.Utilizador2FK);
            return View(userReview);
        }

        // GET: UserReviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UserReview == null)
            {
                return NotFound();
            }

            var userReview = await _context.UserReview.FindAsync(id);
            if (userReview == null)
            {
                return NotFound();
            }
            ViewData["UtilizadorFK"] = new SelectList(_context.Utilizadores, "UserID", "Area", userReview.UtilizadorFK);
            ViewData["Utilizador2FK"] = new SelectList(_context.Utilizadores, "UserID", "Area", userReview.Utilizador2FK);
            return View(userReview);
        }

        // POST: UserReviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdReview,ValueReview,DateReview,UtilizadorFK,Utilizador2FK")] UserReview userReview)
        {
            if (id != userReview.IdReview)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userReview);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserReviewExists(userReview.IdReview))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UtilizadorFK"] = new SelectList(_context.Utilizadores, "UserID", "Area", userReview.UtilizadorFK);
            ViewData["Utilizador2FK"] = new SelectList(_context.Utilizadores, "UserID", "Area", userReview.Utilizador2FK);
            return View(userReview);
        }

        // GET: UserReviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UserReview == null)
            {
                return NotFound();
            }

            var userReview = await _context.UserReview
                .Include(u => u.Utilizador)
                .Include(u => u.Utilizador2)
                .FirstOrDefaultAsync(m => m.IdReview == id);
            if (userReview == null)
            {
                return NotFound();
            }

            return View(userReview);
        }

        // POST: UserReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UserReview == null)
            {
                return Problem("Entity set 'ApplicationDbContext.UserReview'  is null.");
            }
            var userReview = await _context.UserReview.FindAsync(id);
            var idUser = userReview.Utilizador2FK;
            if (userReview != null)
            {
                _context.UserReview.Remove(userReview);
            }
            
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("Details", "Utilizadores", new { id = idUser });
        }

        private bool UserReviewExists(int id)
        {
          return _context.UserReview.Any(e => e.IdReview == id);
        }
    }
}

BookSelling/BookSelling/Controllers/UtilizadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookSelling.Data;
using BookSelling.Models;
using Microsoft.AspNetCore.Identity;

namespace BookSelling.Controllers
{
    public class UtilizadoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<IdentityUser> _userManager;

        public UtilizadoresController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Utilizadores
        public async Task<IActionResult> Index()
        {
              return View(await _context.Utilizadores.ToListAsync());
        }

        // POST: Jogos/CreateRating
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRating(int userId, double nota)
        {

            //variável que vai buscar o Utilizador que escreveu a Review
            var utilizador = _context.Utilizadores.Where(u => u.LinkID == _userManager.GetUserId(User)).FirstOrDefault();

            //Colocar nos dados da Review os daods introduzidos pelo Utilizador
            var review = new UserReview
            {
                ValueReview = nota,
                DateReview = DateTime.Now,
                Utilizador = utilizador,
                Utilizador2FK = userId
            };

            //Adiciona a base de dados a review
            _context.Add(review);
            await _context.SaveChangesAsync();
            //Guarda as alterações feitas na base de dados
            return RedirectToAction(nameof(Details), new { id = userId });
        }

        // GET: Utilizadores/Details/5
        public async Task<IActionResult> Details(int? id, int value, int reviwed)
        {
            int soma = 0;
            int media = 0;
            var result = _context.UserReview.Where(b => b.Utilizador2FK == id);
            int num = _context.UserReview.Count(b => b.Utilizador2FK == id);

            foreach (var item in _context.UserReview)
            {
                foreach (var item2 in _context.Utilizadores)
                {
                    if (item.Utilizador2FK == item2.UserID)
                    {
                        item.Utilizador2 = item2;
                    }
                    if (item.UtilizadorFK == item2.UserID)
                    {
                        item.Utilizador = item2;
                    }
                }
            }
            UserReview item3 = null;
            
            foreach (var item in _context.UserReview)
            {
                if (item.Utilizador2FK == reviwed && User.Identity.Name == item.Utilizador.Email)
                {
                    //item.ValueReview = value;
                    item3 = _context.UserReview.First(a => a == item);
                    item3.ValueReview = value;
                }
            }

            //await _context.SaveChangesAsync();
            _context.SaveChanges();

            if (result.Any())
            {
                foreach (var item in result)
                {
                    soma = soma + (int)item.ValueReview;
                }
                media = soma / num;
                foreach (var item in _context.Utilizadores)
                {
                    if (item.UserID == id)
                    {
                        item.Reputation = media;
                    }
                }
            }

            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }

            var utilizadores = await _context.Utilizadores
                 .Where(a => a.UserID == id)
                                            .Include(a => a.UtilizadoresLeft)
                                            .Include(b => b.UtilizadoresRight)
                                        .FirstOrDefaultAsync();
            if (utilizadores == null)
            {
                return NotFound();
            }

            return View(utilizadores);
        }

        // GET: Utilizadores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Utilizadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserID,UserName,LinkID,Email,Reputation,Area,BooksSold,Telephone")] Utilizadores utilizadores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(utilizadores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(utilizadores);
        }

        // GET: Utilizadores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }

            var utilizadores = await _context.Utilizadores.FindAsync(id);
            if (utilizadores == null)
            {
                return NotFound();
            }
            return View(utilizadores);
        }

        // POST: Utilizadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserID,UserName,LinkID,Email,Reputation,Area,BooksSold,Telephone")] Utilizadores utilizadores, String username, String email)
        {
            if (id != utilizadores.UserID)
            {
                return NotFound();
            }
            ModelState.Remove("UserID");
            ModelState.Remove("LinkID");
            ModelState.Remove("BookSold");
            ModelState.Remove("Reputation");

            //foreach (var user in _context.Utilizadores)
            //{
            //    if (user.Email == email && User.Identity.Name != email)
            //    {
            //        ViewBag.ErrorMessage = "This email is already in use.";
            //        return View(utilizadores);
            //    }
            //}

            //foreach (var user in _context.Utilizadores)
            //{
            //    if (user.UserName == username && User.Identity.Name != email)
            //    {
            //        ViewBag.ErrorMessage = "This username is already in use.";
            //        return View();
            //    }
            //}

            //foreach (var user in _context.Users)
            //{
            //    if (user.Email == User.Identity.Name)
            //    {
            //        var user2 = _context.Users.First(a => a == user);
            //        user2.Email = email;
            //    }
            //}

            //_context.SaveChanges();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(utilizadores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtilizadoresExists(utilizadores.UserID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                //return PartialView("Details", utilizadores);
                return RedirectToAction(nameof(Details), new { id = id });
                //return RedirectToAction(nameof(Details));
            }

            //return PartialView("Details", utilizadores);
            //return View("Details", utilizadores);
            return RedirectToAction(nameof(Details), new { id = id });
        }

        // GET: Utilizadores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }

            var utilizadores = await _context.Utilizadores
                .FirstOrDefaultAsync(m => m.UserID == id);
            if (utilizadores == null)
            {
                return NotFound();
            }

            return View(utilizadores);
        }

        // POST: Utilizadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Utilizadores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Utilizadores'  is null.");
            }
            var utilizadores = await _context.Utilizadores.FindAsync(id);
            if (utilizadores != null)
            {
                _context.Utilizadores.Remove(utilizadores);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UtilizadoresExists(int id)
        {
          return _context.Utilizadores.Any(e => e.UserID == id);
        }
    }
}

BookSelling/BookSelling/Views/Utilizadores/Create.cshtml
@model BookSelling.Models.Utilizadores

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Utilizadores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkID" class="control-label"></label>
                <input asp-for="LinkID" class="form-control" />
                <span asp-validation-for="LinkID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reputation" class="control-label"></label>
                <input asp-for="Reputation" class="form-control" />
                <span asp-validation-for="Reputation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BooksSold" class="control-label"></label>
                <input asp-for="BooksSold" class="form-control" />
                <span asp-validation-for="BooksSold" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookSelling/BookSelling/Views/Utilizadores/Delete.cshtml
@model BookSelling.Models.Utilizadores

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utilizadores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reputation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reputation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BooksSold)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BooksSold)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookSelling/BookSelling/Views/Utilizadores/Details.cshtml
@model BookSelling.Models.Utilizadores

@{
    ViewData["Title"] = "Details";
}

@*<h1>Details</h1>*@

@*<div>
    <h4>Utilizadores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reputation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reputation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BooksSold)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BooksSold)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.UserID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>*@

<section>
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img style=" width: 120px; height: 120px; object-fit:fill; border-radius: 60px" src="~/Logos/logo_user2b.png"/>
            <h5 class="my-3">@Model.UserName</h5>
            <p class="text-muted mb-4">@Model.Email</p>
            @if(User.Identity.IsAuthenticated && Model.Email == User.Identity.Name){
                <button class="btn btn-primary" style="height:35px; margin-right:10px" onclick="location.href = '@Url.Action("Edit","Utilizadores", new { id = Model.UserID})'">Edit</button>
            }
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">@Model.UserName</p>
              </div>
            </div>
            <hr style="background-color:grey">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">@Model.Email</p>
              </div>
            </div>
            <hr style="background-color:grey">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Phone</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">@Model.Telephone</p>
              </div>
            </div>
            <hr style="background-color:grey">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Area</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">@Model.Area</p>
              </div>
            </div>
            <hr style="background-color:grey">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Reputation</p>
              </div>
                @{
                    int reputation = (int) Model.Reputation;
                    if(reputation != 0){
                        @if (@Model.Reputation < 3)
                        {
                            <div style="height: 24px; width: 35px; text-align: center; background-color: red">
                                <a>@reputation</a>
                            </div>
                        }
                        else if (@Model.Reputation == 3)
                        {
                            <div style="height: 24px; width: 35px; text-align: center; background-color: yellow">
                                <a>@reputation</a>
                            </div>
                        }
                        else if (@Model.Reputation > 3)
                        {
                            <div style="height: 24px; width: 35px; text-align: center; background-color: greenyellow">
                                <a>@reputation</a>
                            </div>
                        }
                    }
                    else{
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">This User haven't been reviewed yet.</p>
                          </div>
                    }
                    
                }
            </div>
          </div>
        </div>

        @if (User.Identity.IsAuthenticated && User.Identity.Name != Model.Email)
        {
            @if (1 == 1)
            {
                int flag = 0;
                @foreach (var item in Model.UtilizadoresRight)
                {
                    if (User.Identity.Name == item.Utilizador.Email)
                    {
                        if (item.ValueReview != 0)
                        {
                            flag = 1;
                        }
                    }
                }
                if (flag == 0)
                {
                    <form asp-action="CreateRating">
                        <div style="border-top:20px solid transparent; border-left:15px solid transparent">
                            <input type="hidden" name="userId" value="@Model.UserID" />
                            <div style="border-top: 10px solid transparent; border-bottom: 25px solid transparent">
                                <a style="font-weight: bold">Review: </a><input required type="number" name="nota" min="1" max="5" text-align="center" maxlength="1" placeholder="1 a 5" />
                                <input type="submit" value="Add Review" class="btn btn-primary" />
                            </div>
                        </div>
                    </form>
                }
            }
        }

        @if (User.Identity.IsAuthenticated && User.Identity.Name != Model.Email)
        {
            @foreach (var item in Model.UtilizadoresRight)
            {
                if (@item.Utilizador.Email == User.Identity.Name)
                {
                    <div style="border-left:30px solid transparent;">
                        <dl class="row">
                            <dt>
                                <a>Your Review:</a>
                            </dt>
                            <dd class="col-sm-10" style="object-fit: fill;">
                                @if (@item.ValueReview < 3)
                                {
                                    <div style="height: 24px; width: 35px; text-align: center; background-color: red">
                                        <a>@item.ValueReview</a>
                                    </div>
                                }
                                else if (@item.ValueReview == 3)
                                {
                                    <div style="height: 24px; width: 35px; text-align: center; background-color: yellow">
                                        <a>@item.ValueReview</a>
                                    </div>
                                }
                                else if (@item.ValueReview > 3)
                                {
                                    <div style="height: 24px; width: 35px; text-align: center; background-color: greenyellow">
                                        <a>@item.ValueReview</a>
                                    </div>
                                }
                            </dd>
                            <div>
                                <button class="btn btn-primary" style="height:35px; margin-right:10px" onclick="location.href = '@Url.Action("Edit","UserReviews", new { id = item.IdReview})'">Edit</button>
                                <button class="btn btn-danger" style="height:35px; margin-right:10px" onclick="location.href = '@Url.Action("Delete","UserReviews", new { id = item.IdReview})'">Delete</button>
                            </div>
                        </dl>
                    </div>
                }
            }
        }
  </div>
</section>

BookSelling/BookSelling/Views/Utilizadores/Index.cshtml
@model IEnumerable<BookSelling.Models.Utilizadores>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Reputation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BooksSold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telephone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LinkID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reputation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BooksSold)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.UserID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.UserID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.UserID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>